# Generated by Django 5.2.4 on 2025-08-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinyurl", "0002_alter_urlstore_hash_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlstore",
            name="input_url",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
